# Generated by Django 6.0.2 on 2026-04-04 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_trial_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='has_sol',
            field=models.BooleanField(default=False),
        ),
    ]
