# Generated by Django 6.0.2 on 2026-08-26 10:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0017_storage_capacity_foundation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="storagecapacitygrant",
            name="user",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="storage_capacity_grants", to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ProductPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_type', models.CharField(choices=[('one_time', 'One Time'), ('monthly', 'Monthly'), ('annual', 'Annual')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('active', models.BooleanField(default=True)),
                ('effective_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('effective_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='billing.product')),
            ],
            options={
                'ordering': ['product', 'price_type', '-effective_from'],
            },
        ),
        migrations.CreateModel(
            name='ProviderStorageCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=120)),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('physical_capacity_bytes', models.PositiveBigIntegerField(blank=True, null=True)),
                ('stored_bytes', models.PositiveBigIntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-period_start', 'provider'],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='provider_storage_cost_nonneg')],
            },
        ),
        migrations.CreateModel(
            name='StoragePurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity_bytes_snapshot', models.PositiveBigIntegerField()),
                ('capacity_label_snapshot', models.CharField(blank=True, default='', max_length=120)),
                ('price_amount_snapshot', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency_snapshot', models.CharField(max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('purchased_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('payment_reference', models.CharField(blank=True, default='', max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('capacity_grant', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='storage_purchase', to='billing.storagecapacitygrant')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='storage_purchases', to='billing.product')),
                ('product_price', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='storage_purchases', to='billing.productprice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='storage_purchases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-purchased_at', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='productprice',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='product_price_amount_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='storagepurchase',
            constraint=models.CheckConstraint(condition=models.Q(('capacity_bytes_snapshot__gt', 0)), name='storage_purchase_capacity_pos'),
        ),
        migrations.AddConstraint(
            model_name='storagepurchase',
            constraint=models.CheckConstraint(condition=models.Q(('price_amount_snapshot__gte', 0)), name='storage_purchase_price_nonneg'),
        ),
    ]
