# Generated by Django 6.0.2 on 2026-08-28 06:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0019_seed_storage_launch_prices'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreCheckout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('checkout_created', 'Checkout Created'), ('paid', 'Paid'), ('fulfilled', 'Fulfilled'), ('failed', 'Failed'), ('expired', 'Expired')], default='pending', max_length=30)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('recurring_amount_snapshot', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('one_time_amount_snapshot', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('due_today_snapshot', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('selection_snapshot', models.JSONField(default=dict)),
                ('quote_snapshot', models.JSONField(default=dict)),
                ('stripe_checkout_session_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('stripe_customer_id', models.CharField(blank=True, default='', max_length=255)),
                ('stripe_subscription_id', models.CharField(blank=True, default='', max_length=255)),
                ('stripe_payment_intent_id', models.CharField(blank=True, default='', max_length=255)),
                ('fulfilled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('storage_purchase', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='store_checkout', to='billing.storagepurchase')),
                ('tool_entitlement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='store_checkouts', to='billing.toolentitlement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='store_checkouts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('recurring_amount_snapshot__gte', 0)), name='store_checkout_recurring_amount_nonneg'), models.CheckConstraint(condition=models.Q(('one_time_amount_snapshot__gte', 0)), name='store_checkout_one_time_amount_nonneg'), models.CheckConstraint(condition=models.Q(('due_today_snapshot__gte', 0)), name='store_checkout_due_today_nonneg')],
            },
        ),
    ]
