# Generated by Django 6.0.2 on 2026-02-15 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0002_changerequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="max_negotiation_rounds",
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AddField(
            model_name="contract",
            name="negotiation_round",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="contractversion",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("sent", "Sent"),
                    ("change_requested", "Change Requested"),
                    ("signed", "Signed"),
                    ("superseded", "Superseded"),
                    ("archived", "Archived"),
                    ("rejected", "Rejected"),
                ],
                default="draft",
                max_length=25,
            ),
        ),
        migrations.DeleteModel(
            name="ChangeRequest",
        ),
    ]
