# Generated by Django 6.0.2 on 2026-02-15 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0003_contract_max_negotiation_rounds_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contract",
            old_name="negotiation_round",
            new_name="negotiation_rounds_used",
        ),
        migrations.RemoveField(
            model_name="contract",
            name="max_negotiation_rounds",
        ),
        migrations.AlterField(
            model_name="contractversion",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("sent", "Sent"),
                    ("negotiating", "Negotiating"),
                    ("signed", "Signed"),
                    ("superseded", "Superseded"),
                    ("archived", "Archived"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
    ]
