# Generated by Django 6.0.2 on 2026-02-16 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0004_rename_negotiation_round_contract_negotiation_rounds_used_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='negotiation_rounds_used',
        ),
        migrations.AddField(
            model_name='contract',
            name='max_versions',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='contractversion',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('negotiating', 'Negotiating'), ('signed', 'Signed'), ('superseded', 'Superseded'), ('archived', 'Archived'), ('rejected', 'Rejected')], default='draft', max_length=20),
        ),
    ]
