# Generated by Django 6.0.2 on 2026-02-17 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0006_requestchange'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestchange',
            name='message',
            field=models.TextField(),
        ),
    ]
