# Generated by Django 6.0.2 on 2026-02-17 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0007_alter_requestchange_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='structure_type',
            field=models.CharField(choices=[('ONE_TIME', 'One-Time Service'), ('ONGOING', 'Ongoing Service'), ('COLLABORATIVE', 'Collaborative Relationship'), ('RESOLUTION', 'Resolution Contract')], default='ONE_TIME', max_length=20),
        ),
    ]
