# Generated by Django 6.0.2 on 2026-02-18 00:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0008_contract_structure_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Obligation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('recurrence_interval_days', models.PositiveIntegerField(blank=True, help_text='If set, obligation recurs every X days.', null=True)),
                ('recurrence_count', models.PositiveIntegerField(blank=True, help_text='How many times this obligation repeats.', null=True)),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('due', 'Due'), ('fulfilled', 'Fulfilled'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obligations', to='contracts.contract')),
                ('from_party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obligations_owed', to=settings.AUTH_USER_MODEL)),
                ('to_party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obligations_due', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
