# Generated by Django 6.0.2 on 2026-02-18 15:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0009_obligation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractObligation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('installment_number', models.PositiveIntegerField()),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('due_date', models.DateTimeField()),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('due', 'Due'), ('grace', 'Grace'), ('overdue', 'Overdue'), ('defaulted', 'Defaulted'), ('resolved', 'Resolved')], default='pending', max_length=20)),
                ('is_defaulted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_obligations_links', to='contracts.contract')),
                ('obligee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receivable_obligations', to=settings.AUTH_USER_MODEL)),
                ('obligor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owed_obligations', to=settings.AUTH_USER_MODEL)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obligations', to='contracts.contractversion')),
            ],
            options={
                'ordering': ['due_date'],
            },
        ),
    ]
