# Generated by Django 6.0.2 on 2026-02-18 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0010_contractobligation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractobligation',
            name='state',
            field=models.CharField(choices=[('active', 'Active'), ('due', 'Due'), ('grace', 'Grace'), ('overdue', 'Overdue'), ('defaulted', 'Defaulted'), ('resolved', 'Resolved')], default='active', max_length=20),
        ),
    ]
