# Generated by Django 6.0.2 on 2026-02-19 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0011_alter_contractobligation_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractobligation',
            name='state',
            field=models.CharField(choices=[('pending', 'Pending'), ('due', 'Due'), ('grace', 'Grace'), ('overdue', 'Overdue'), ('defaulted', 'Defaulted'), ('resolved', 'Resolved')], default='pending', max_length=20),
        ),
    ]
