# Generated by Django 6.0.2 on 2026-02-27 00:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0012_alter_contractobligation_state'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='initiator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_contracts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contractobligation',
            name='state',
            field=models.CharField(choices=[('active', 'active'), ('due', 'Due'), ('grace', 'Grace'), ('overdue', 'Overdue'), ('defaulted', 'Defaulted'), ('resolved', 'Resolved')], default='active', max_length=20),
        ),
    ]
