# Generated by Django 6.0.2 on 2026-03-10 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0013_alter_contract_initiator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='state',
            field=models.CharField(default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='obligation',
            name='obligation_type',
            field=models.CharField(choices=[('payment', 'Payment Obligation'), ('service', 'Service Obligation')], default='payment', max_length=20),
        ),
        migrations.AddField(
            model_name='obligation',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contractobligation',
            name='state',
            field=models.CharField(choices=[('active', 'Active'), ('due', 'Due'), ('grace', 'Grace'), ('overdue', 'Overdue'), ('defaulted', 'Defaulted'), ('resolved', 'Resolved')], default='active', max_length=20),
        ),
    ]
