# Generated by Django 6.0.2 on 2026-03-17 23:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0014_contract_state_obligation_obligation_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractServiceObligation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('due_date', models.DateTimeField()),
                ('state', models.CharField(choices=[('active', 'Active'), ('due', 'Due'), ('overdue', 'Overdue'), ('resolved', 'Resolved')], default='active', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_obligations', to='contracts.contract')),
                ('obligee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_receivable', to=settings.AUTH_USER_MODEL)),
                ('obligor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_owed', to=settings.AUTH_USER_MODEL)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_obligations', to='contracts.contractversion')),
            ],
        ),
    ]
