# Generated by Django 6.0.2 on 2026-03-18 23:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0015_contractserviceobligation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObligationExecutionSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('closed', 'Closed')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment_obligation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='execution_sessions', to='contracts.contractobligation')),
                ('service_obligation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='execution_sessions', to='contracts.contractserviceobligation')),
            ],
        ),
        migrations.CreateModel(
            name='ObligationExecutionEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=100)),
                ('task', models.CharField(blank=True, max_length=255, null=True)),
                ('observation', models.CharField(blank=True, max_length=255, null=True)),
                ('summary', models.TextField()),
                ('estimated_duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('estimated_cost_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('estimated_cost_currency', models.CharField(blank=True, max_length=10, null=True)),
                ('planned_execution_time', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='contracts.obligationexecutionsession')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
