# Generated by Django 6.0.2 on 2026-03-20 12:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0016_obligationexecutionsession_obligationexecutionevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractValueAdjustment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('adjustment_type', models.CharField(choices=[('additional_charge', 'Additional Charge'), ('lateness_adjustment', 'Lateness Adjustment')], max_length=50)),
                ('mode', models.CharField(choices=[('fixed_amount', 'Fixed Amount'), ('percentage', 'Percentage')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('summary', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='value_adjustments', to='contracts.contract')),
                ('execution_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='value_adjustments', to='contracts.obligationexecutionevent')),
                ('payment_obligation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='value_adjustments', to='contracts.contractobligation')),
                ('service_obligation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='value_adjustments', to='contracts.contractserviceobligation')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
