# Generated by Django 6.0.2 on 2026-03-21 00:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0018_contractapprovalrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractObligationPromotion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('promotion_type', models.CharField(choices=[('event_to_service_obligation', 'Event to Service Obligation')], default='event_to_service_obligation', max_length=50)),
                ('summary', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obligation_promotions', to='contracts.contract')),
                ('parent_service_obligation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_promotions', to='contracts.contractserviceobligation')),
                ('promoted_service_obligation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='origin_promotions', to='contracts.contractserviceobligation')),
                ('source_execution_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='contracts.obligationexecutionevent')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
