# Generated by Django 5.2 on 2026-06-23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("contracts", "0030_lifecycle_item_origin_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="LifecycleItemUserState",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("title_override", models.CharField(blank=True, max_length=255, null=True)),
                ("description_override", models.TextField(blank=True, null=True)),
                ("due_date_override", models.DateTimeField(blank=True, null=True)),
                ("amount_override", models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ("responsible_party_override", models.CharField(blank=True, max_length=255, null=True)),
                ("payment_method_override", models.CharField(blank=True, max_length=255, null=True)),
                ("status_override", models.CharField(blank=True, max_length=20, null=True)),
                ("notes", models.TextField(blank=True, default="")),
                ("reminder_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("lifecycle_item", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="user_states", to="contracts.lifecycleitem")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="lifecycle_item_states", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["lifecycle_item", "user"], name="contracts_lifec_user_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(fields=("lifecycle_item", "user"), name="contracts_lifecycleitem_user_unique"),
                ],
            },
        ),
    ]
