# Generated by Django 6.0.2 on 2026-06-27 18:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0032_lifecycle_agreement_performance_ready'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LifecycleItemAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='lifecycle_item_attachments/%Y/%m/%d/')),
                ('original_filename', models.CharField(max_length=255)),
                ('content_type', models.CharField(blank=True, default='', max_length=120)),
                ('file_size', models.PositiveBigIntegerField(default=0)),
                ('kind', models.CharField(choices=[('proof_receipt', 'Proof / Receipt')], default='proof_receipt', max_length=40)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lifecycle_item_attachments', to='contracts.contract')),
                ('lifecycle_agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_attachments', to='contracts.lifecycleagreement')),
                ('lifecycle_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='contracts.lifecycleitem')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_lifecycle_item_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['lifecycle_item', '-created_at'], name='lifec_attach_item_idx'), models.Index(fields=['lifecycle_agreement', '-created_at'], name='lifec_attach_agree_idx')],
            },
        ),
    ]
