# Generated by Codex on 2026-06-28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0033_lifecycle_item_attachment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LifecycleItemResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('response', models.CharField(choices=[('received', 'Received'), ('still_waiting', 'Still waiting'), ('not_received', 'Not received')], max_length=40)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lifecycle_item_responses', to='contracts.contract')),
                ('lifecycle_agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_responses', to='contracts.lifecycleagreement')),
                ('lifecycle_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counterparty_responses', to='contracts.lifecycleitem')),
                ('responder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lifecycle_item_responses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at', '-created_at'],
                'indexes': [models.Index(fields=['lifecycle_item', '-updated_at'], name='lifec_resp_item_idx'), models.Index(fields=['lifecycle_agreement', '-updated_at'], name='lifec_resp_agree_idx')],
                'constraints': [models.UniqueConstraint(fields=('lifecycle_item', 'responder'), name='lifec_item_response_unique')],
            },
        ),
    ]
