# Generated by Codex on 2026-06-28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0034_lifecycle_item_response'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LifecycleItemMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lifecycle_item_messages', to='contracts.contract')),
                ('lifecycle_agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_messages', to='contracts.lifecycleagreement')),
                ('lifecycle_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='contracts.lifecycleitem')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lifecycle_item_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at', 'id'],
                'indexes': [models.Index(fields=['lifecycle_item', 'created_at'], name='lifec_msg_item_idx'), models.Index(fields=['lifecycle_agreement', 'created_at'], name='lifec_msg_agree_idx')],
            },
        ),
    ]
