# Generated by Codex on 2026-06-28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0035_lifecycle_item_message"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LifecycleChangeProposal",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("proposal_type", models.CharField(choices=[("add_on", "Add-on"), ("change_order", "Change Order")], max_length=20)),
                ("status", models.CharField(choices=[("proposed", "Proposed"), ("accepted", "Accepted"), ("rejected", "Rejected")], default="proposed", max_length=20)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("responsible_party", models.CharField(blank=True, choices=[("initiator", "Initiator"), ("counterparty", "Counterparty")], default="", max_length=20)),
                ("amount", models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ("due_date", models.DateField(blank=True, null=True)),
                ("note", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("affected_item", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="change_proposals", to="contracts.lifecycleitem")),
                ("contract", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="lifecycle_change_proposals", to="contracts.contract")),
                ("decided_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="decided_lifecycle_change_proposals", to=settings.AUTH_USER_MODEL)),
                ("lifecycle_agreement", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="change_proposals", to="contracts.lifecycleagreement")),
                ("proposed_by", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="lifecycle_change_proposals", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["-created_at", "-updated_at"],
                "indexes": [
                    models.Index(fields=["lifecycle_agreement", "status"], name="lifec_change_agree_status_idx"),
                    models.Index(fields=["contract", "-created_at"], name="lifec_change_contract_idx"),
                ],
            },
        ),
    ]
