# Generated by Codex on 2026-06-29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0036_lifecycle_change_proposal"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="lifecyclechangeproposal",
            name="decision_note",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.CreateModel(
            name="LifecycleChangeProposalMessage",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("body", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("contract", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="lifecycle_change_proposal_messages", to="contracts.contract")),
                ("lifecycle_agreement", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="change_proposal_messages", to="contracts.lifecycleagreement")),
                ("proposal", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="messages", to="contracts.lifecyclechangeproposal")),
                ("sender", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="lifecycle_change_proposal_messages", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["created_at", "id"],
                "indexes": [
                    models.Index(fields=["proposal", "created_at"], name="lifec_chmsg_prop_idx"),
                    models.Index(fields=["lifecycle_agreement", "created_at"], name="lifec_chmsg_agree_idx"),
                ],
            },
        ),
    ]
