# Generated by Codex on 2026-06-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0037_lifecycle_change_proposal_decision_chat"),
    ]

    operations = [
        migrations.AddField(
            model_name="lifecyclechangeproposal",
            name="final_due_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="lifecyclechangeproposal",
            name="final_amount",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name="lifecyclechangeproposal",
            name="final_responsible_party",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
