# Generated by Codex on 2026-06-30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0038_lifecycle_change_proposal_final_terms"),
    ]

    operations = [
        migrations.AddField(
            model_name="lifecyclechangeproposal",
            name="generation_mode",
            field=models.CharField(
                choices=[
                    ("single", "One-time obligation"),
                    ("before_each_payment_deadline", "Before each payment deadline"),
                ],
                default="single",
                max_length=40,
            ),
        ),
    ]
