# Generated by Django 6.0.2 on 2026-06-30 22:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0039_lifecycle_change_proposal_generation_mode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractExtractionRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stage', models.CharField(choices=[('prepare', 'Prepare'), ('final_pre_sign', 'Final Pre-Sign'), ('post_sign_backfill', 'Post-Sign Backfill'), ('external_import', 'External Import')], max_length=40)),
                ('source_kind', models.CharField(choices=[('editor_html', 'Editor HTML'), ('final_editor_html', 'Final Editor HTML'), ('uploaded_contract', 'Uploaded Contract'), ('agreement_exchange_version', 'Agreement Exchange Version'), ('signed_version', 'Signed Version'), ('pasted_text', 'Pasted Text')], max_length=40)),
                ('source_hash', models.CharField(blank=True, default='', max_length=128)),
                ('engine_name', models.CharField(blank=True, default='', max_length=120)),
                ('engine_version', models.CharField(blank=True, default='', max_length=80)),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('superseded', 'Superseded')], default='running', max_length=20)),
                ('warnings', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extraction_runs', to='contracts.contract')),
                ('contract_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extraction_runs', to='contracts.contractversion')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_contract_extraction_runs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ContractExtractionCandidate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('candidate_type', models.CharField(choices=[('payment', 'Payment'), ('service_work', 'Service Work'), ('deadline', 'Deadline'), ('responsibility', 'Responsibility'), ('notice', 'Notice'), ('deposit', 'Deposit'), ('inspection', 'Inspection'), ('delivery', 'Delivery'), ('recurring_obligation', 'Recurring Obligation'), ('other', 'Other')], max_length=40)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('responsible_party', models.CharField(blank=True, default='', max_length=255)),
                ('beneficiary_party', models.CharField(blank=True, default='', max_length=255)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(blank=True, default='', max_length=8)),
                ('recurrence', models.JSONField(blank=True, default=dict)),
                ('source_clause_text', models.TextField(blank=True, default='')),
                ('source_clause_key', models.CharField(blank=True, default='', max_length=255)),
                ('source_location', models.JSONField(blank=True, default=dict)),
                ('confidence_score', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('missing_terms', models.JSONField(blank=True, default=list)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('review_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('edited', 'Edited')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_lifecycle_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_extraction_candidates', to='contracts.lifecycleitem')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extraction_candidates', to='contracts.contract')),
                ('contract_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extraction_candidates', to='contracts.contractversion')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_contract_extraction_candidates', to=settings.AUTH_USER_MODEL)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='contracts.contractextractionrun')),
            ],
        ),
        migrations.AddIndex(
            model_name='contractextractionrun',
            index=models.Index(fields=['contract', 'stage', 'status'], name='contract_extract_run_state_idx'),
        ),
        migrations.AddIndex(
            model_name='contractextractionrun',
            index=models.Index(fields=['contract_version', 'stage'], name='contract_extract_run_ver_idx'),
        ),
        migrations.AddIndex(
            model_name='contractextractionrun',
            index=models.Index(fields=['source_hash'], name='contract_extract_run_hash_idx'),
        ),
        migrations.AddIndex(
            model_name='contractextractionrun',
            index=models.Index(fields=['created_at'], name='contract_extract_run_created_idx'),
        ),
        migrations.AddIndex(
            model_name='contractextractioncandidate',
            index=models.Index(fields=['contract', 'review_status'], name='contract_extract_cand_review_idx'),
        ),
        migrations.AddIndex(
            model_name='contractextractioncandidate',
            index=models.Index(fields=['run', 'candidate_type'], name='contract_extract_cand_type_idx'),
        ),
        migrations.AddIndex(
            model_name='contractextractioncandidate',
            index=models.Index(fields=['contract_version', 'review_status'], name='contract_extract_cand_ver_idx'),
        ),
        migrations.AddIndex(
            model_name='contractextractioncandidate',
            index=models.Index(fields=['due_date'], name='contract_extract_cand_due_idx'),
        ),
        migrations.AddIndex(
            model_name='contractextractioncandidate',
            index=models.Index(fields=['confidence_score'], name='contract_extract_cand_conf_idx'),
        ),
    ]
