# Generated by Django 6.0.2 on 2026-08-27 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0040_contractextractionrun_contractextractioncandidate_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='contractextractioncandidate',
            new_name='ctr_extr_cand_review_idx',
            old_name='contract_extract_cand_review_idx',
        ),
        migrations.RenameIndex(
            model_name='contractextractionrun',
            new_name='ctr_extr_run_created_idx',
            old_name='contract_extract_run_created_idx',
        ),
    ]
