# Generated by Django 6.0.2 on 2026-04-03 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='is_draft_document',
            field=models.BooleanField(default=False),
        ),
    ]
