# Generated by Django 6.0.2 on 2026-09-01 22:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0002_upload_is_draft_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoredObject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('backend', models.CharField(default='default', max_length=80)),
                ('bucket', models.CharField(blank=True, default='', max_length=255)),
                ('object_key', models.CharField(max_length=1024)),
                ('size_bytes', models.PositiveBigIntegerField()),
                ('content_type', models.CharField(blank=True, default='', max_length=255)),
                ('checksum', models.CharField(blank=True, default='', max_length=255)),
                ('checksum_algorithm', models.CharField(blank=True, default='', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['backend', 'bucket'], name='stored_obj_backend_bucket_idx'), models.Index(fields=['object_key'], name='stored_obj_key_idx'), models.Index(fields=['created_at'], name='stored_obj_created_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('size_bytes__gte', 0)), name='stored_object_size_non_negative'), models.UniqueConstraint(fields=('backend', 'bucket', 'object_key'), name='stored_object_physical_unique')],
            },
        ),
    ]
