# Generated by Django 6.0.2 on 2026-09-01 23:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0003_storedobject'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserObjectAccess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_visible', models.BooleanField(default=True)),
                ('counts_toward_quota', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('removed_at', models.DateTimeField(blank=True, null=True)),
                ('stored_object', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_accesses', to='uploads.storedobject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stored_object_accesses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='user_obj_acc_user_active_idx'), models.Index(fields=['stored_object', 'is_active'], name='user_obj_acc_obj_active_idx'), models.Index(fields=['is_visible'], name='user_obj_acc_visible_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'stored_object'), name='user_object_access_user_object_unique')],
            },
        ),
    ]
