# Generated by Codex on 2026-09-02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("uploads", "0004_userobjectaccess"),
    ]

    operations = [
        migrations.AddField(
            model_name="upload",
            name="stored_object",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="uploads",
                to="uploads.storedobject",
            ),
        ),
    ]
