# Generated by Codex on 2026-09-02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("uploads", "0005_upload_stored_object"),
    ]

    operations = [
        migrations.AlterField(
            model_name="upload",
            name="file_type",
            field=models.CharField(
                choices=[
                    ("pdf", "PDF"),
                    ("image", "Image"),
                    ("video", "Video"),
                    ("audio", "Audio"),
                    ("slides", "Slides"),
                    ("document", "Document"),
                    ("other", "Other"),
                ],
                max_length=20,
            ),
        ),
    ]
