# Generated by Django 6.0.2 on 2026-09-02 11:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0006_upload_file_type_audio_other'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VaultShare',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vault_shares', to=settings.AUTH_USER_MODEL)),
                ('stored_object', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vault_shares', to='uploads.storedobject')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['owner', 'revoked_at'], name='vault_share_owner_revoked_idx'), models.Index(fields=['stored_object', 'revoked_at'], name='vault_share_obj_revoked_idx'), models.Index(fields=['expires_at'], name='vault_share_expires_idx')],
            },
        ),
    ]
