# Generated by Django 6.0.2 on 2026-09-09 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0009_vaultfolder_upload_vault_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='vault_removed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
