# Generated by Django 6.0.2 on 2026-04-01 02:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0020_add_contract_role_switch_request'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_type', models.CharField(choices=[('contract_created', 'Contract Created'), ('contract_updated', 'Contract Updated'), ('version_created', 'Version Created'), ('version_signed', 'Version Signed'), ('version_rejected', 'Version Rejected'), ('role_switch_requested', 'Role Switch Requested'), ('role_switch_confirmed', 'Role Switch Confirmed'), ('obligation_resolved', 'Obligation Resolved'), ('payment_obligation_resolved', 'Payment Obligation Resolved'), ('payment_created', 'Payment Created'), ('payment_confirmed', 'Payment Confirmed'), ('payment_failed', 'Payment Failed'), ('payment_cancelled', 'Payment Cancelled'), ('payment_refunded', 'Payment Refunded'), ('payment_reversed', 'Payment Reversed'), ('approval_requested', 'Approval Requested'), ('approval_granted', 'Approval Granted'), ('approval_rejected', 'Approval Rejected'), ('session_held', 'Session Held')], max_length=50)),
                ('description', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_log', to='contracts.contract')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['contract', '-created_at'], name='activity_co_contrac_1148b6_idx')],
            },
        ),
    ]
