# Generated by Django 6.0.2 on 2026-05-24 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractactivity',
            name='activity_type',
            field=models.CharField(choices=[('contract_created', 'Contract Created'), ('contract_updated', 'Contract Updated'), ('version_created', 'Version Created'), ('version_signed', 'Version Signed'), ('version_rejected', 'Version Rejected'), ('counterparty_viewed', 'Counterparty Viewed'), ('counterparty_requested_changes', 'Counterparty Requested Changes'), ('counterparty_accepted', 'Counterparty Accepted'), ('counterparty_rejected', 'Counterparty Rejected'), ('counterparty_signed', 'Counterparty Signed'), ('role_switch_requested', 'Role Switch Requested'), ('role_switch_confirmed', 'Role Switch Confirmed'), ('obligation_resolved', 'Obligation Resolved'), ('payment_obligation_resolved', 'Payment Obligation Resolved'), ('payment_created', 'Payment Created'), ('payment_confirmed', 'Payment Confirmed'), ('payment_failed', 'Payment Failed'), ('payment_cancelled', 'Payment Cancelled'), ('payment_refunded', 'Payment Refunded'), ('payment_reversed', 'Payment Reversed'), ('approval_requested', 'Approval Requested'), ('approval_granted', 'Approval Granted'), ('approval_rejected', 'Approval Rejected'), ('session_held', 'Session Held')], max_length=50),
        ),
    ]
