# Generated by Django 6.0.2 on 2026-04-04 21:47

import backend.sol.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sol',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sol_id', models.CharField(default=backend.sol.models._sol_id, editable=False, max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('frequency', models.CharField(choices=[('weekly', 'Weekly'), ('biweekly', 'Biweekly'), ('monthly', 'Monthly')], max_length=20)),
                ('contribution_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(choices=[('USD', 'US Dollar'), ('CAD', 'Canadian Dollar'), ('MXN', 'Mexican Peso'), ('BRL', 'Brazilian Real'), ('ARS', 'Argentine Peso'), ('COP', 'Colombian Peso'), ('CLP', 'Chilean Peso'), ('PEN', 'Peruvian Sol'), ('HTG', 'Haitian Gourde'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('CHF', 'Swiss Franc'), ('SEK', 'Swedish Krona'), ('NOK', 'Norwegian Krone'), ('DKK', 'Danish Krone'), ('AED', 'UAE Dirham'), ('SAR', 'Saudi Riyal'), ('EGP', 'Egyptian Pound'), ('MAD', 'Moroccan Dirham'), ('QAR', 'Qatari Riyal'), ('KWD', 'Kuwaiti Dinar'), ('ZAR', 'South African Rand'), ('NGN', 'Nigerian Naira'), ('GHS', 'Ghanaian Cedi'), ('KES', 'Kenyan Shilling'), ('UGX', 'Ugandan Shilling'), ('TZS', 'Tanzanian Shilling'), ('ETB', 'Ethiopian Birr'), ('XOF', 'West African CFA Franc'), ('XAF', 'Central African CFA Franc'), ('RWF', 'Rwandan Franc'), ('MZN', 'Mozambican Metical'), ('ZMW', 'Zambian Kwacha'), ('JPY', 'Japanese Yen'), ('CNY', 'Chinese Yuan'), ('INR', 'Indian Rupee'), ('KRW', 'South Korean Won'), ('SGD', 'Singapore Dollar'), ('HKD', 'Hong Kong Dollar'), ('AUD', 'Australian Dollar'), ('NZD', 'New Zealand Dollar'), ('TWD', 'Taiwan Dollar'), ('THB', 'Thai Baht'), ('IDR', 'Indonesian Rupiah'), ('MYR', 'Malaysian Ringgit'), ('PHP', 'Philippine Peso'), ('PKR', 'Pakistani Rupee'), ('BDT', 'Bangladeshi Taka'), ('VND', 'Vietnamese Dong')], default='USD', max_length=10)),
                ('tip_expectation', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_private', models.BooleanField(default=True)),
                ('sol_type', models.CharField(choices=[('single', 'Single Cycle'), ('recurring', 'Recurring')], default='single', max_length=20)),
                ('start_date', models.DateField()),
                ('expected_end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('co_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='co_managed_sols', to=settings.AUTH_USER_MODEL)),
                ('primary_manager', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='managed_sols', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SolMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=50)),
                ('employer', models.CharField(blank=True, max_length=200)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=200)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=50)),
                ('is_bonup_member', models.BooleanField(default=False)),
                ('hand_number', models.PositiveIntegerField()),
                ('has_received', models.BooleanField(default=False)),
                ('is_manager_participant', models.BooleanField(default=False)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('bonup_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sol_memberships', to=settings.AUTH_USER_MODEL)),
                ('sol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='sol.sol')),
            ],
            options={
                'ordering': ['hand_number'],
                'unique_together': {('sol', 'hand_number')},
            },
        ),
        migrations.CreateModel(
            name='SolContract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('agreed_contribution_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('agreed_hand_number', models.PositiveIntegerField()),
                ('agreed_tip_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('contract_text', models.TextField()),
                ('signed_by_member', models.BooleanField(default=False)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='sol.sol')),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contract', to='sol.solmember')),
            ],
        ),
        migrations.CreateModel(
            name='SolNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sol_notes', to=settings.AUTH_USER_MODEL)),
                ('sol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='sol.sol')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SolPayout',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payout_id', models.CharField(default=backend.sol.models._pay_id, editable=False, max_length=20, unique=True)),
                ('cycle_number', models.PositiveIntegerField()),
                ('hand_number', models.PositiveIntegerField()),
                ('expected_date', models.DateField()),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('expected_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('actual_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('paid', 'Paid'), ('delayed', 'Delayed'), ('missed', 'Missed')], default='upcoming', max_length=20)),
                ('was_rearranged', models.BooleanField(default=False)),
                ('rearranged_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('original_recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payouts_original', to='sol.solmember')),
                ('rearranged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sol_rearrangements', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payouts_received', to='sol.solmember')),
                ('sol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='sol.sol')),
            ],
            options={
                'ordering': ['cycle_number', 'hand_number'],
            },
        ),
        migrations.CreateModel(
            name='SolTip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(choices=[('USD', 'US Dollar'), ('CAD', 'Canadian Dollar'), ('MXN', 'Mexican Peso'), ('BRL', 'Brazilian Real'), ('ARS', 'Argentine Peso'), ('COP', 'Colombian Peso'), ('CLP', 'Chilean Peso'), ('PEN', 'Peruvian Sol'), ('HTG', 'Haitian Gourde'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('CHF', 'Swiss Franc'), ('SEK', 'Swedish Krona'), ('NOK', 'Norwegian Krone'), ('DKK', 'Danish Krone'), ('AED', 'UAE Dirham'), ('SAR', 'Saudi Riyal'), ('EGP', 'Egyptian Pound'), ('MAD', 'Moroccan Dirham'), ('QAR', 'Qatari Riyal'), ('KWD', 'Kuwaiti Dinar'), ('ZAR', 'South African Rand'), ('NGN', 'Nigerian Naira'), ('GHS', 'Ghanaian Cedi'), ('KES', 'Kenyan Shilling'), ('UGX', 'Ugandan Shilling'), ('TZS', 'Tanzanian Shilling'), ('ETB', 'Ethiopian Birr'), ('XOF', 'West African CFA Franc'), ('XAF', 'Central African CFA Franc'), ('RWF', 'Rwandan Franc'), ('MZN', 'Mozambican Metical'), ('ZMW', 'Zambian Kwacha'), ('JPY', 'Japanese Yen'), ('CNY', 'Chinese Yuan'), ('INR', 'Indian Rupee'), ('KRW', 'South Korean Won'), ('SGD', 'Singapore Dollar'), ('HKD', 'Hong Kong Dollar'), ('AUD', 'Australian Dollar'), ('NZD', 'New Zealand Dollar'), ('TWD', 'Taiwan Dollar'), ('THB', 'Thai Baht'), ('IDR', 'Indonesian Rupiah'), ('MYR', 'Malaysian Ringgit'), ('PHP', 'Philippine Peso'), ('PKR', 'Pakistani Rupee'), ('BDT', 'Bangladeshi Taka'), ('VND', 'Vietnamese Dong')], default='USD', max_length=10)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tips_given', to='sol.solmember')),
                ('sol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tips', to='sol.sol')),
                ('to_manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sol_tips_received', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SolContribution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('late', 'Late'), ('missed', 'Missed')], default='pending', max_length=20)),
                ('due_date', models.DateField()),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='sol.sol')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='sol.solmember')),
                ('payout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='sol.solpayout')),
            ],
            options={
                'ordering': ['due_date'],
                'unique_together': {('payout', 'member')},
            },
        ),
    ]
