"""Closed vocabularies shared by the versioned control records."""
from enum import StrEnum


class ValidationError(ValueError):
    """Invalid control data. Messages identify fields, never echo supplied values."""


class AuthorityError(ValidationError):
    """The supplied trusted context does not authorize an operation."""


class TaskState(StrEnum):
    PROPOSED = "PROPOSED"
    INSPECTING = "INSPECTING"
    SPEC_READY = "SPEC_READY"
    FOUNDER_APPROVED = "FOUNDER_APPROVED"
    ASSIGNED = "ASSIGNED"
    IN_PROGRESS = "IN_PROGRESS"
    READY_FOR_QA = "READY_FOR_QA"
    QA_REVIEW = "QA_REVIEW"
    CHANGES_REQUESTED = "CHANGES_REQUESTED"
    QA_PASSED = "QA_PASSED"
    FOUNDER_APPROVED_FOR_INTEGRATION = "FOUNDER_APPROVED_FOR_INTEGRATION"
    INTEGRATED = "INTEGRATED"
    PUSHED = "PUSHED"
    CLOSED = "CLOSED"
    BLOCKED = "BLOCKED"
    CONTRACT_CONFLICT = "CONTRACT_CONFLICT"
    INTERRUPTED = "INTERRUPTED"
    ABANDONED = "ABANDONED"


class Role(StrEnum):
    ARCHITECT = "ARCHITECT"
    FRONTEND_ENGINEERING = "FRONTEND_ENGINEERING"
    BACKEND_ENGINEERING = "BACKEND_ENGINEERING"
    INTEGRATION_QA = "INTEGRATION_QA"
    PRODUCT = "PRODUCT"
    ENGINEERING_RESEARCH = "ENGINEERING_RESEARCH"
    DATA_BI = "DATA_BI"
    CUSTOMER_EXPERIENCE = "CUSTOMER_EXPERIENCE"
    MARKETING = "MARKETING"
    SECURITY_RELEASE = "SECURITY_RELEASE"
    DOCUMENTATION_KNOWLEDGE = "DOCUMENTATION_KNOWLEDGE"
    EDUCATION_TRAINING = "EDUCATION_TRAINING"
    FOUNDER = "FOUNDER"  # Human authority, never an AgentRecord/ExecutionGrant.


class Priority(StrEnum):
    P0 = "P0"
    P1 = "P1"
    P2 = "P2"
    P3 = "P3"


class PathKind(StrEnum):
    FILE = "FILE"
    DIRECTORY = "DIRECTORY"
    GLOB = "GLOB"


class ResourceType(StrEnum):
    MIGRATION = "MIGRATION"
    BACKEND_TEST_DB = "BACKEND_TEST_DB"
    CONCURRENCY_TEST_DB = "CONCURRENCY_TEST_DB"
    FRONTEND_BUILD = "FRONTEND_BUILD"
    DEPENDENCY_INSTALL = "DEPENDENCY_INSTALL"
    DEPENDENCY_LOCKFILE = "DEPENDENCY_LOCKFILE"
    BACKEND_DEV_SERVER = "BACKEND_DEV_SERVER"
    FRONTEND_DEV_SERVER = "FRONTEND_DEV_SERVER"
    GIT_INTEGRATION = "GIT_INTEGRATION"
    PRODUCTION_DEPLOYMENT = "PRODUCTION_DEPLOYMENT"


class ReservationMode(StrEnum):
    EXCLUSIVE = "EXCLUSIVE"
    CAPACITY = "CAPACITY"


class CandidateState(StrEnum):
    READY_FOR_QA = "READY_FOR_QA"
    QA_REVIEW = "QA_REVIEW"
    CHANGES_REQUESTED = "CHANGES_REQUESTED"
    QA_PASSED = "QA_PASSED"
    FOUNDER_APPROVED_FOR_INTEGRATION = "FOUNDER_APPROVED_FOR_INTEGRATION"
    INVALIDATED = "INVALIDATED"


class RecordKind(StrEnum):
    FINDING = "FINDING"
    CONFLICT = "CONFLICT"
    DECISION = "DECISION"


class RecordType(StrEnum):
    TECHNICAL = "TECHNICAL"
    SCOPE = "SCOPE"
    INTERFACE = "INTERFACE"
    SECURITY = "SECURITY"
    PRODUCT = "PRODUCT"
    PRIORITY = "PRIORITY"
    BUDGET = "BUDGET"


class Severity(StrEnum):
    CRITICAL = "CRITICAL"
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"


class ApprovalAction(StrEnum):
    APPROVE_SPEC = "APPROVE_SPEC"
    APPROVE_INTEGRATION = "APPROVE_INTEGRATION"
    APPROVE_PUSH = "APPROVE_PUSH"
    REJECT = "REJECT"
    REVOKE = "REVOKE"


class EventType(StrEnum):
    TASK_CREATED = "TASK_CREATED"
    TASK_APPROVED = "TASK_APPROVED"
    AGENT_ASSIGNED = "AGENT_ASSIGNED"
    WORK_STARTED = "WORK_STARTED"
    LOCK_ACQUIRED = "LOCK_ACQUIRED"
    LOCK_RELEASED = "LOCK_RELEASED"
    SPEC_CONFLICT = "SPEC_CONFLICT"
    CANDIDATE_CREATED = "CANDIDATE_CREATED"
    CANDIDATE_INVALIDATED = "CANDIDATE_INVALIDATED"
    QA_PASSED = "QA_PASSED"
    QA_REJECTED = "QA_REJECTED"
    FOUNDER_APPROVED = "FOUNDER_APPROVED"
    APPROVAL_REVOKED = "APPROVAL_REVOKED"
    INTEGRATED = "INTEGRATED"
    PUSHED = "PUSHED"
    INTERRUPTED = "INTERRUPTED"
    RECOVERED = "RECOVERED"
    BUDGET_PAUSED = "BUDGET_PAUSED"
