# Generated by Django 6.0.2 on 2026-05-24 07:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai", "0001_initial"),
        ("contracts", "0025_fix_lawwn_entity"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkflowState",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("current_state", models.CharField(choices=[("uploaded", "Uploaded"), ("analyzing", "Analyzing"), ("review_ready", "Review Ready"), ("counter_draft_ready", "Counter Draft Ready"), ("version_created", "Version Created"), ("sent_to_counterparty", "Sent To Counterparty")], default="uploaded", max_length=40)),
                ("completed_states", models.JSONField(blank=True, default=list)),
                ("pending_states", models.JSONField(blank=True, default=list)),
                ("state_timestamps", models.JSONField(blank=True, default=dict)),
                ("source_label", models.CharField(blank=True, default="", max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("contract", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="workflow_states", to="contracts.contract")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="workflow_states", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.AddIndex(
            model_name="workflowstate",
            index=models.Index(fields=["user", "-updated_at"], name="ai_workflow_user_id_b71a0d_idx"),
        ),
        migrations.AddIndex(
            model_name="workflowstate",
            index=models.Index(fields=["contract", "-updated_at"], name="ai_workflow_contrac_9adb1b_idx"),
        ),
    ]
