# Generated by Django 6.0.2 on 2026-05-24 08:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_workflowstate'),
        ('contracts', '0025_fix_lawwn_entity'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowstate',
            name='created_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_states', to='contracts.contractversion'),
        ),
        migrations.AddField(
            model_name='workflowstate',
            name='sent_to_counterparty_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.CreateModel(
            name='ReviewResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('summary', models.TextField(blank=True, default='')),
                ('identified_risks', models.JSONField(blank=True, default=list)),
                ('unclear_clauses', models.JSONField(blank=True, default=list)),
                ('negotiation_opportunities', models.JSONField(blank=True, default=list)),
                ('suggested_changes', models.JSONField(blank=True, default=list)),
                ('key_terms', models.JSONField(blank=True, default=dict)),
                ('questions', models.JSONField(blank=True, default=list)),
                ('ai_metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_results', to='ai.aiconversation')),
                ('workflow', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review_result', to='ai.workflowstate')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='CounterDraft',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('discarded', 'Discarded')], default='draft', max_length=20)),
                ('generated_revised_contract', models.TextField(blank=True, default='')),
                ('selected_requested_changes', models.JSONField(blank=True, default=list)),
                ('user_negotiation_instructions', models.TextField(blank=True, default='')),
                ('summary', models.TextField(blank=True, default='')),
                ('concerning_clauses', models.JSONField(blank=True, default=list)),
                ('negotiation_strategy', models.JSONField(blank=True, default=dict)),
                ('ai_metadata', models.JSONField(blank=True, default=dict)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counter_drafts', to='ai.aiconversation')),
                ('created_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_counter_drafts', to='contracts.contractversion')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counter_drafts', to='ai.workflowstate')),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['workflow', '-updated_at'], name='ai_counterd_workflo_1417f6_idx'), models.Index(fields=['status', '-updated_at'], name='ai_counterd_status_c0ce36_idx')],
            },
        ),
    ]
