# Generated by Django 6.0.2 on 2026-05-24 09:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0003_workflowstate_created_version_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowstate',
            name='counterparty_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='workflowstate',
            name='counterparty_requested_changes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='workflowstate',
            name='counterparty_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counterparty_workflow_states', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workflowstate',
            name='current_state',
            field=models.CharField(choices=[('uploaded', 'Uploaded'), ('analyzing', 'Analyzing'), ('review_ready', 'Review Ready'), ('counter_draft_ready', 'Counter Draft Ready'), ('version_created', 'Version Created'), ('sent_to_counterparty', 'Sent To Counterparty'), ('counterparty_viewed', 'Counterparty Viewed'), ('counterparty_requested_changes', 'Counterparty Requested Changes'), ('counterparty_counter_generated', 'Counterparty Counter Generated'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('signed', 'Signed')], default='uploaded', max_length=40),
        ),
    ]
