# Generated by Django 6.0.2 on 2026-05-24 09:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0004_workflowstate_counterparty_email_and_more'),
        ('contracts', '0025_fix_lawwn_entity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NegotiationComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comment_type', models.CharField(choices=[('general', 'General'), ('clarification_request', 'Clarification Request'), ('change_request', 'Change Request'), ('risk_note', 'Risk Note'), ('acceptance_note', 'Acceptance Note')], default='general', max_length=40)),
                ('clause_reference', models.CharField(blank=True, default='', max_length=255)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='negotiation_comments', to=settings.AUTH_USER_MODEL)),
                ('version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='negotiation_comments', to='contracts.contractversion')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='negotiation_comments', to='ai.workflowstate')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['workflow', 'created_at'], name='ai_negotiat_workflo_af9f1e_idx'), models.Index(fields=['version', 'created_at'], name='ai_negotiat_version_8990a5_idx')],
            },
        ),
    ]
