const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')

const frontend = path.resolve(__dirname, '..')
const read = (file) => fs.readFileSync(path.join(frontend, file), 'utf8')
const app = read('src/App.tsx')
const gate = read('src/components/RequireBlackboardAccess.tsx')
const transition = read('src/components/BlackboardEntryTransition.tsx')
const transitionStyles = read('src/components/blackboard-entry.css')
const shell = read('src/components/layout/PlatformShell.tsx')
const home = read('src/pages/BonupHub.tsx')

assert.match(app, /RequireBlackboardAccess/)
assert.match(app, /BlackboardEntryTransition/)
assert.match(app, /<RequireBlackboardAccess>/)
assert.match(app, /<BlackboardEntryTransition>/)
assert.match(app, /<Route index element={<Navigate to="workspace" replace \/>} \/>/)
assert.match(app, /<Route path="dashboard" element={<Dashboard \/>} \/>/)
assert.match(app, /<Route path="workspace" element={<WorkflowDashboard \/>} \/>/)
assert.match(gate, /has_blackbod_access !== true/)
assert.doesNotMatch(gate, /localStorage/)
assert.match(transition, /workspaceRevealMs: 6000/)
assert.match(transition, /landingDurationMs: 2000/)
assert.match(transition, /totalDurationMs: 8000/)
assert.doesNotMatch(transition, /totalDurationMs: (?:[0-9]|[1-9][0-9]{1,2}|[1-7][0-9]{3})\b/)
assert.match(transition, /setPhase\('arriving'\)/)
assert.match(transition, /BLACKBOD_ENTRY_TIMELINE\.workspaceRevealMs/)
assert.match(transition, /useLocation/)
assert.match(transition, /location\.state\?\.blackbodEntry === true/)
assert.match(transition, /if \(!isBoundaryEntry \|\| phase === 'complete'\) return children/)
assert.match(transition, /--blackbod-landing-duration/)
assert.match(transition, /BLACKBOD_ENTRY_TIMELINE\.totalDurationMs/)
assert.match(transition, /window\.clearTimeout\(completeTimer\)/)
assert.match(transition, /blackboard-entry-screen/)
assert.match(transition, /BLACKBOD/)
assert.doesNotMatch(transition, /BLACKBOARD/)
assert.match(transition, /Preparing your workspace\.\.\./)
assert.match(transition, /aria-label="Entering Blackbod"/)
assert.doesNotMatch(transition, /setTimeout\([^\n]*3000/)
assert.match(transitionStyles, /@media \(prefers-reduced-motion: reduce\)/)
assert.match(transitionStyles, /blackboard-entry-progress/)
assert.match(transitionStyles, /blackboard-entry-panel-in/)
assert.match(transitionStyles, /blackboard-entry-surface-out/)
assert.match(transitionStyles, /blackboard-entry-destination-in/)
assert.match(transitionStyles, /var\(--blackbod-landing-duration, 2000ms\) cubic-bezier\(0\.22, 1, 0\.36, 1\)/)
assert.match(transitionStyles, /opacity: 0\.62/)
assert.match(transitionStyles, /translateY\(16px\) scale\(0\.99\)/)
assert.match(transitionStyles, /3700ms 1800ms/)

// Both Home actions retain their existing Blackboard destinations.
assert.match(home, /to="\/apps\/blackbod\/contracts\/new"/)
assert.match(home, /to="\/apps\/blackbod"/)
assert.match(home, /state=\{\{ blackbodEntry: true \}\}/)
assert.match(shell, /to: '\/apps\/blackbod\/workspace'/)
assert.match(shell, /blackbodEntry: true/)
assert.match(home, /to="\/apps\/blackbod"/)
assert.match(home, /to="\/apps\/blackbod\/contracts\/new"/)

// Nislo has its own route shell and does not use BlackboardEntryTransition.
const nisloRoute = app.slice(app.indexOf('path="/apps/nislo"'))
assert.doesNotMatch(nisloRoute, /BlackboardEntryTransition/)

console.log('Blackboard entitlement and entry assertions passed')
