# Generated by Django 6.0.2 on 2026-04-02 07:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('live_sessions', '0003_livesession_presentation_controller'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrepSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('live_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prep_sessions', to='live_sessions.livesession')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prep_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrepNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prep_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_items', to='negotiation_prep.prepsession')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrepDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('file_url', models.CharField(max_length=2048)),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('image', 'Image'), ('video', 'Video'), ('slides', 'Slides')], max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('prep_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='negotiation_prep.prepsession')),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
    ]
