# Generated by Django 6.0.2 on 2026-04-28 07:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_type', models.CharField(choices=[('soul_entity', 'Soul Entity'), ('business_entity', 'Business Entity')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Entity',
                'verbose_name_plural': 'Entities',
            },
        ),
        migrations.CreateModel(
            name='SoulEntity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='soul_entity', to='bonup.entity')),
                ('soul', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='soul_entity', to='bonup.soul')),
            ],
            options={
                'verbose_name': 'Soul Entity',
                'verbose_name_plural': 'Soul Entities',
            },
        ),
    ]
