# Generated by Django 6.0.2 on 2026-03-31 02:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContractTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=100)),
                ('subcategory', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('structure_type', models.CharField(choices=[('ONE_TIME', 'One-Time Service'), ('ONGOING', 'Ongoing Service')], default='ONE_TIME', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('tier_required', models.CharField(choices=[('free', 'Free'), ('basic', 'Basic'), ('premium', 'Premium'), ('enterprise', 'Enterprise')], default='free', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TemplateClause',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('clause_type', models.CharField(choices=[('scope', 'Scope of Services'), ('payment', 'Payment Terms'), ('cancellation', 'Cancellation Policy'), ('liability', 'Limitation of Liability'), ('termination', 'Termination'), ('risk', 'Assumption of Risk'), ('confidentiality', 'Confidentiality'), ('general', 'General')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('is_conditional', models.BooleanField(default=False)),
                ('condition_description', models.CharField(blank=True, default='', max_length=500)),
                ('is_required', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clauses', to='contract_templates.contracttemplate')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TemplateObligationPattern',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('obligation_type', models.CharField(choices=[('service', 'Service Only'), ('payment', 'Payment Only'), ('both', 'Service and Payment')], default='both', max_length=20)),
                ('frequency_type', models.CharField(choices=[('one_time', 'One Time'), ('per_session', 'Per Session'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('installment', 'Installment')], default='one_time', max_length=20)),
                ('amount_token', models.CharField(blank=True, default='', max_length=100)),
                ('installments_token', models.CharField(blank=True, default='', max_length=100)),
                ('interval_days_token', models.CharField(blank=True, default='', max_length=100)),
                ('template', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='obligation_pattern', to='contract_templates.contracttemplate')),
            ],
        ),
        migrations.CreateModel(
            name='TemplateGuidedField',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('field_key', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=200)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('choice', 'Choice'), ('boolean', 'Boolean')], max_length=20)),
                ('choices', models.JSONField(blank=True, null=True)),
                ('is_required', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guided_fields', to='contract_templates.contracttemplate')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('template', 'field_key')},
            },
        ),
    ]
