# Generated by Django 6.0.2 on 2026-03-31 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract_templates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='templateguidedfield',
            name='condition_field_key',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='templateguidedfield',
            name='condition_value',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='templateobligationpattern',
            name='payment_model_token',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
