# Generated by Django 6.0.2 on 2026-04-08 04:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract_templates', '0002_templateguidedfield_condition_field_key_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObligationTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('content', models.TextField()),
                ('category', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contract_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='obligation_templates', to='contract_templates.contracttemplate')),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PaymentTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('content', models.TextField()),
                ('schedule_type', models.CharField(choices=[('one_time', 'One Time'), ('installment', 'Installment'), ('recurring', 'Recurring'), ('milestone', 'Milestone')], default='one_time', max_length=50)),
                ('category', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contract_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_templates', to='contract_templates.contracttemplate')),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
    ]
