# Generated by Django 6.0.2 on 2026-04-02 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_sessions', '0002_alter_livesession_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='livesession',
            name='presentation_controller',
            field=models.CharField(choices=[('initiator', 'Initiator'), ('counterparty', 'Counterparty')], default='initiator', max_length=20),
        ),
    ]
