# Generated by Django 6.0.2 on 2026-04-02 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0020_add_contract_role_switch_request'),
        ('live_sessions', '0003_livesession_presentation_controller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livesession',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='live_sessions', to='contracts.contract'),
        ),
    ]
