# Generated by Django 6.0.2 on 2026-09-26 21:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='is_discoverable',
            field=models.BooleanField(default=True, editable=False),
        ),
        migrations.CreateModel(
            name='CommunityJoinRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to='community.community')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_community_join_requests', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='community_join_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['community', 'status'], name='community_c_communi_5eac75_idx'), models.Index(fields=['user', 'status'], name='community_c_user_id_1ba4e7_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('community', 'user'), name='community_join_request_pending_unique')],
            },
        ),
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='friend_requests_received', to=settings.AUTH_USER_MODEL)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='friend_requests_sent', to=settings.AUTH_USER_MODEL)),
                ('user_a', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='friendships_as_a', to=settings.AUTH_USER_MODEL)),
                ('user_b', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='friendships_as_b', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user_a', 'status'], name='community_f_user_a__4c957f_idx'), models.Index(fields=['user_b', 'status'], name='community_f_user_b__1d3f8e_idx'), models.Index(fields=['recipient', 'status'], name='community_f_recipie_b41376_idx')],
                'constraints': [models.UniqueConstraint(fields=('user_a', 'user_b'), name='friendship_pair_unique'), models.CheckConstraint(condition=models.Q(('user_a', models.F('user_b')), _negated=True), name='friendship_no_self')],
            },
        ),
    ]
