# Generated by Django 6.0.2 on 2026-06-15 02:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agreement_exchange', '0002_restart_fields'),
        ('contracts', '0027_add_signed_contract_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreementexchange',
            name='staged_contract_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staged_for_exchanges', to='contracts.contractversion'),
        ),
        migrations.AlterField(
            model_name='agreementexchange',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('viewed', 'Viewed'), ('counterparty_review', 'Counterparty review'), ('changes_requested', 'Changes requested'), ('initiator_review', 'Initiator review'), ('initiator_editing', 'Initiator editing'), ('updated_version_sent', 'Updated version sent'), ('ready_to_sign', 'Ready to sign'), ('signed', 'Signed'), ('rejected', 'Rejected')], default='draft', max_length=32),
        ),
    ]
