# Generated by Django 6.0.2 on 2026-03-18 18:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservedBonId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bon_id', models.CharField(db_index=True, editable=False, max_length=13, unique=True)),
                ('reason', models.CharField(default='binary_reserved', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['bon_id'],
            },
        ),
        migrations.CreateModel(
            name='BonUserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bon_id', models.CharField(db_index=True, editable=False, max_length=13, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bon_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['bon_id'],
            },
        ),
    ]
