# Generated by Django 6.0.2 on 2026-04-04 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_add_profile_fields_billing_invitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonuserprofile',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('ht', 'Haitian Creole'), ('es', 'Spanish'), ('fr', 'French'), ('pt', 'Portuguese'), ('ar', 'Arabic'), ('sw', 'Swahili')], default='en', max_length=5),
        ),
    ]
